const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
  showcaseSidebar: [{ type: 'autogenerated', dirName: 'showcase' }],
  knowledgeBaseSidebar: [{ type: 'autogenerated', dirName: 'knowledge-base' }],
  documentationSidebar: [{ type: 'autogenerated', dirName: 'avstudio-editor' }],
};

module.exports = sidebars;