const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
  manualSidebar: [{ type: 'autogenerated', dirName: 'manual' }],
  knowledgeBaseSidebar: [{ type: 'autogenerated', dirName: 'knowledge-base' }],
};

module.exports = sidebars;